### ISSUE TITLE
plotly tooltips

### ISSUE THREAD

**Issue by ashcroftp** [covid-19-Re/chCovidDashboard#6]
How complicated would it be to introduce tooltips for the data points, to get the exact percentages.
Something like this might work: https://plotly-r.com/controlling-tooltips.html#tooltip-text-ggplotly
Not sure of how much it will slow things down though :/

**Comment by dcangst** [comment]
I tried to use ggplotly once in the very beginning without success. I didn't spend too much time on it but will try again now

**Comment by dcangst** [comment]
completed in 5e622afa7d6fb1dd205bc56dc2ce084efed4d310
