### ISSUE TITLE
Present recent data as uncertain

### ISSUE THREAD

**Issue by chaoran-chen** [covid-19-Re/chCovidDashboard#7]
The data from the past month should be highlighted in a way that shows that the data are not stable yet. A possible solution could be giving them a gray color.

(Idea of @tgvaughan)

**Comment by tgvaughan** [comment]
Actually this was @tanja819's idea. :-)

**Comment by jriou** [comment]
I don't see what make data in the last month less certain than before. Certainly data from the last few days, maybe a week, can still be incomplete because of reporting delays, but why one month?

**Comment by tanja819** [comment]
We plot the chance of a person diagnosed on day xx to be eventually hospitalized. if xx = yesterday, then most people are not yet hospitalized while the ratio hospitalization/confirmed cases will go down and eventually stabilize. I argued that after 1 month, either you recovered or went to hospital, thus the ratio is trustworthy. pending on the delay we see empirically in the data between confirmation adn hospitalization, the ratio may be trustworthy already after 2 weeks or so? but not only days?

**Comment by jriou** [comment]
I see now, you're right!
